config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :team_members
  end

  resource :programed_course_sessions do
    get :autocomplete_person_last_name, on: :collection
  end
  
  resources :courses do 
    resources :programed_courses, shallow: true do
      resources :enrollments, shallow: true 
      resources :programed_course_sessions, shallow: true   
    end
  end
  

  resources :people

  get 'teachers' => 'teachers#index'

   root 'people#index'

end

app/controllers/programed_courses_controller.rb
class ProgramedCoursesController < ApplicationController
  before_action :set_programed_course, only: [ :show, :edit, :update, :destroy]
  before_action :set_course, only: [:index, :new, :create]
  before_action :set_available_supervisors, only: [:new, :create, :edit]
  before_action :authenticate_user!


  # GET /programed_courses
  # GET /programed_courses.json
  def index
    @programed_courses = ProgramedCourse.where(course_id: @course.id).all.order(:start_date)
  end

  # GET /programed_courses/1
  # GET /programed_courses/1.json
  def show
  end

  # GET /programed_courses/new
  def new
    @programed_course = ProgramedCourse.new
  end

  # GET /programed_courses/1/edit
  def edit
  end

  # POST /programed_courses
  # POST /programed_courses.json
  def create
    @programed_course = ProgramedCourse.new(programed_course_params)
    @programed_course.course_id = @course.id

    respond_to do |format|
      if @programed_course.save
        format.html { redirect_to @course, notice: 'Programed course was successfully created.' }
        format.json { render :show, status: :created, location: @programed_course }
      else
        format.html { render :new }
        format.json { render json: @programed_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programed_courses/1
  # PATCH/PUT /programed_courses/1.json
  def update
    respond_to do |format|
      if @programed_course.update(programed_course_params)
        format.html { redirect_to course_programed_courses_path(@programed_course.course_id), notice: 'Programed course was successfully updated.' }
        format.json { render :show, status: :ok, location: @programed_course }
      else
        format.html { render :edit }
        format.json { render json: @programed_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programed_courses/1
  # DELETE /programed_courses/1.json
  def destroy
    @programed_course.destroy
    respond_to do |format|
      format.html { redirect_to course_programed_courses_path(@course), notice: 'Programed course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programed_course
      @programed_course = ProgramedCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    
    def programed_course_params
      params.require(:programed_course).permit(:start_date, :close_date, :details, :supervisor_id) 
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_available_supervisors
      @supervisors = Person.where(:teacher => true)
    end

end

app/helpers/programed_courses_helper.rb
module ProgramedCoursesHelper
end

app/views/programed_courses/_form.html.haml
= simple_form_for ([@course, @programed_course]) do |f|
  = f.error_notification
  = f.input :start_date, label: "Fecha de inicio", as: :date, html5: true, input_html: { class: 'form-control' }
  = f.input :close_date, label: "Fecha de clausura", as: :date, html5: true, input_html: { class: 'form-control' }
  = f.input :details, label: "Detalles",  input_html: { class: 'form-control' }
  = f.association :supervisor, collection: @supervisors, label_method: :full_name, value_method: :id 


  = f.button :submit, "Guardar"

app/views/programed_courses/edit.html.haml
%h1 Editar curso programado

= render 'form'

= link_to 'Mostrar', @programed_course, class: "btn btn-default"
\|
= link_to 'Atras', course_programed_courses_path(@programed_course.course_id) , class: "btn btn-default"

app/views/programed_courses/index.html.haml
%p
  %h2 
    Lista de generaciones para cursos:
    %span
      %b=@course.name

%table.table
  %thead
    %tr
      %td
      %th Fecha de inicio
      %th Fecha de clausura
      %th Detalles
      %th Supervisor
      %th

  %tbody
    - @programed_courses.each do |programed_course|
      %tr
        %td= link_to 'Ver', programed_course_programed_course_sessions_path(programed_course)
        %td= link_to programed_course.start_date, programed_course_programed_course_sessions_path(programed_course)
        %td= link_to programed_course.close_date, programed_course_programed_course_sessions_path(programed_course)
        %td= programed_course.details
        -if programed_course.supervisor
          %td= programed_course.supervisor.full_name
        - else
          %td Sin registro de maestro
        %td= link_to 'Editar', edit_programed_course_path(programed_course)
-#        %td= link_to 'Destroy', [@course, programed_course], :method => :delete, :data => { :confirm => 'Are you sure?' }


%br

= link_to 'Atras', courses_path, class: "btn btn-default"
= link_to 'Nueva Generación', new_course_programed_course_path, class: "btn btn-default"

app/views/programed_courses/new.html.haml
%h1 Nueva generación

= render 'form'
%br
= link_to 'Atras', course_programed_courses_path, class: "btn btn-default"

app/views/programed_courses/show.html.haml
%p#notice= notice


= link_to 'Editar', edit_programed_course_path(@programed_course), class: "btn btn-default"

= link_to 'Atras', @programed_course, class: "btn btn-default"