config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :team_members
  end

  resource :programed_course_sessions do
    get :autocomplete_person_last_name, on: :collection
  end
  
  resources :courses do 
    resources :programed_courses, shallow: true do
      resources :enrollments, shallow: true 
      resources :programed_course_sessions, shallow: true   
    end
  end
  

  resources :people

  get 'teachers' => 'teachers#index'

   root 'people#index'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student, :class_name => "Person"
  belongs_to :programed_course
  validates :student_id, :presence => true
  validates :programed_course_id, :presence => true
    
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_programed_courses, only: [:show, :edit, :update, :destroy, :new]
  before_action :authenticate_user!

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    set_programed_course
    @enrollment = @programed_course.enrollments.create(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to programed_course_programed_course_sessions_path(@programed_course.id), notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { redirect_to programed_course_programed_course_sessions_path(@programed_course.id), notice: 'Esa persona no esta registrada.'  }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to programed_course_programed_course_sessions_path(@enrollment.programed_course_id), notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :programed_course_id)
    end

    def set_programed_courses
      @programed_courses = ProgramedCourse.all
    end


    def set_programed_course
      @programed_course = ProgramedCourse.find(params[:programed_course_id])
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.haml
= simple_form_for(@enrollment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :student, label: "Alumno", label_method: :full_name
    = f.association :programed_course, label: "Curso programado", collection: @programed_courses, label_method: :course_name, value_method: :id 


  .form-actions
    = f.button :submit, "Inscribir"

app/views/enrollments/edit.html.haml
%h1 Editar Inscripción

= render 'form'

= link_to 'Mostrar', @enrollment, class: "btn btn-default" 
\|
= link_to 'Atras', enrollments_path, class: "btn btn-default" 

app/views/enrollments/index.html.haml
%h1 Lista de inscripciones


%table.table
  %thead
    %tr
      %th Alumno
      %th Curso Programado
      %th
      %th
      %th

  %tbody
    - @enrollments.each do |enrollment|
      %tr

        %td= enrollment.student.full_name
        %td= enrollment.programed_course.course_name
        %td= link_to 'Mostrar', enrollment
        %td= link_to 'Editar', edit_enrollment_path(enrollment)
        %td= link_to 'Destruir', enrollment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

/ = link_to 'Nueva Inscripción', new_enrollment_path, class: "btn btn-default" 

app/views/enrollments/new.html.haml
%h1 Nueva Inscripción

= render 'form'

= link_to 'Atras', enrollments_path, class: "btn btn-default" 

app/views/enrollments/show.html.haml
%p#notice= notice

%p
  %b Alumno:
  = @enrollment.student
%p
  %b Curso programado:
  = @enrollment.programed_course

= link_to 'Editar', edit_enrollment_path(@enrollment), class: "btn btn-default" 
\|
= link_to 'Volver a curso programado', programed_course_programed_course_sessions_path(@enrollment.programed_course_id), class: "btn btn-default" 