config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :team_members
  end

  resource :programed_course_sessions do
    get :autocomplete_person_last_name, on: :collection
  end
  
  resources :courses do 
    resources :programed_courses, shallow: true do
      resources :enrollments, shallow: true 
      resources :programed_course_sessions, shallow: true   
    end
  end
  

  resources :people

  get 'teachers' => 'teachers#index'

   root 'people#index'

end

app/models/programed_course_session.rb
class ProgramedCourseSession < ActiveRecord::Base
  belongs_to :programed_course, dependent: :destroy
  belongs_to :teacher, :class_name => "Person", dependent: :destroy



end

app/controllers/programed_course_sessions_controller.rb
class ProgramedCourseSessionsController < ApplicationController
  autocomplete :person, :last_name, :full => true, limit: 15, :column_name => 'last_name', :display_value => 'full_name', :full_model=>true 
  before_action :set_programed_course_session, only: [:show, :edit, :update, :destroy]
  before_action :set_programed_course, only: [:index, :new, :create]
  before_action :set_available_teachers, only: [:new, :create, :edit]
  before_action :authenticate_user!


  # GET /programed_course_sessions
  # GET /programed_course_sessions.json
  def index
    @programed_course_sessions = ProgramedCourseSession.where(programed_course_id: @programed_course.id).all
    @enrollments = Enrollment.where(programed_course_id: @programed_course.id).all
    @enrollment = Enrollment.new
    @enrollment.programed_course_id=@programed_course.id
    set_teams
    @team = Team.new
  end

  # GET /programed_course_sessions/1
  # GET /programed_course_sessions/1.json
  def show
  end

  # GET /programed_course_sessions/new
  def new
    @programed_course_session = ProgramedCourseSession.new
    @programed_course_session.programed_course_id = @programed_course.id
  end

  # GET /programed_course_sessions/1/edit
  def edit
  end

  # POST /programed_course_sessions
  # POST /programed_course_sessions.json
  def create
    @programed_course_session = ProgramedCourseSession.new(programed_course_session_params)
    @programed_course_session.programed_course_id = @programed_course.id

    respond_to do |format|
      if @programed_course_session.save
        format.html { redirect_to programed_course_programed_course_sessions_path(@programed_course), notice: 'Programed course session was successfully created.' }
        format.json { render :show, status: :created, location: @programed_course_session }
      else
        format.html { render :new }
        format.json { render json: @programed_course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programed_course_sessions/1
  # PATCH/PUT /programed_course_sessions/1.json
  def update
    respond_to do |format|
      if @programed_course_session.update(programed_course_session_params)
        format.html { redirect_to programed_course_programed_course_sessions_path(@programed_course_session.programed_course_id), notice: 'Programed course session was successfully updated.' }
        format.json { render :show, status: :ok, location: @programed_course_session }
      else
        format.html { render :edit }
        format.json { render json: @programed_course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programed_course_sessions/1
  # DELETE /programed_course_sessions/1.json
  def destroy
    @programed_course_session.destroy
    respond_to do |format|
      format.html { redirect_to programed_course_programed_course_sessions_path(@programed_course_session), notice: 'Programed course session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programed_course_session
      @programed_course_session = ProgramedCourseSession.find(params[:id])
    end

    def set_programed_course
      @programed_course = ProgramedCourse.find(params[:programed_course_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programed_course_session_params
      params.require(:programed_course_session).permit(:programed_course_id, :session_number, :topic, :date, :teacher_id)
    end

    def set_available_teachers
      @teachers = Person.where(:teacher => true)
    end

    def set_teams
      @teams = Team.where(programed_course: @programed_course)
    end

end

app/helpers/programed_course_sessions_helper.rb
module ProgramedCourseSessionsHelper
end

app/views/programed_course_sessions/_enrollment.html.haml
= simple_form_for [@programed_course, @programed_course.enrollments.build] do |f|
  = f.error_notification
  .form-inputs
    = f.input :student, label:"Alumno (Buscar por apellido)", :url => autocomplete_person_last_name_programed_course_sessions_path, as: :autocomplete, input_html: { class: 'form-input form-control' }, :id_element => '#student_id'
    =f.hidden_field :student_id, :id => "student_id"

  .form-actions
    = f.button :submit, "Inscribir", class: "form-button btn btn-default"

app/views/programed_course_sessions/_form.html.haml
= simple_form_for([@course, @programed_course, @programed_course_session]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :session_number, label: "Numero de Sesión"
    = f.input :topic, label: "Tema"
    = f.input :date, label: "Fecha"
    = f.association :teacher, collection: @teachers, label_method: :full_name, value_method: :id, label: "Moderador"


  .form-actions
    = f.button :submit, "Guardar", class: "btn btn-default" 

app/views/programed_course_sessions/_team.html.haml
= simple_form_for [@team] do |f|
  = f.error_notification
  .form-inputs
    = f.input :person, label:"Coordinador (Buscar por apellido)", :url => autocomplete_person_last_name_programed_course_sessions_path, as: :autocomplete, input_html: { class: 'form-input form-control' }, :id_element => '#person_id'
    =f.hidden_field :person_id, :id => "person_id"
    =f.hidden_field :programed_course_id, value: @programed_course.id

  .form-actions
    = f.button :submit, "Crear Equipo", class: "form-button btn btn-default"

app/views/programed_course_sessions/edit.html.haml
%h1 Editar Sesión

= render 'form'

= link_to 'Mostrar', @programed_course_session, class: "btn btn-default" 
\|
= link_to 'Atras', programed_course_programed_course_sessions_path(@programed_course_session.programed_course_id), class: "btn btn-default" 

app/views/programed_course_sessions/index.html.haml
.row
  .col-lg-12
    - if @programed_course.supervisor
      %h3= "Supervisor de curso: #{@programed_course.supervisor.full_name}"
    - else
      %h3 Supervisor de curso: Sin supervisor registrado  
.row
  .col-lg-8
    %h2 Lista de sesiones
    %table.table
      %thead
        %tr
          %th Número de sesión
          %th Moderador
          %th Tema
          %th Fecha
          %th
          %th
          %th

      %tbody
      - @programed_course_sessions.each do |programed_course_session|
        %tr
          %td= programed_course_session.session_number
          - if programed_course_session.teacher
            %td= programed_course_session.teacher.full_name
          - else
            %td Sin registro de maestro
          %td= programed_course_session.topic
          %td= programed_course_session.date
          %td= link_to 'Editar', edit_programed_course_session_path(programed_course_session)
          %td= link_to 'Destruir', programed_course_session_path(programed_course_session), :method => :delete, :data => { :confirm => 'Are you sure?' }
    %br
    = link_to 'Atras', course_programed_courses_path(@programed_course.course_id), class: "btn btn-default"
    = link_to 'Nueva sesión', new_programed_course_programed_course_session_path, class: "btn btn-default" 
  

  .col-lg-4
    %h2 Alumnos Inscritos
    %table.table
      %thead
        %tr
          %th Nombre
          %th 
      
      %tbody
      - @enrollments.each do |enrollment|
        %tr
          -if enrollment.student.full_name
            %td=link_to enrollment.student.full_name, person_path(enrollment.student.id)
          -else
            %td=link_to enrollment.student_id, person_path(enrollment.student.id)
          %th= link_to "Destruir", enrollment, method: :delete, data: { confirm: "Are you sure ? "}  
    = render 'enrollment'

-#        %td= link_to 'Mostrar', course_programed_course_programed_course_session
-#        %td= link_to 'Editar', edit_programed_course_session_path(programed_course_session)
.row
  .col-lg-8
    %h2 Equipos
    %table.table
      %thead
        %tr
          %th Coordinador
          %th Integrantes
          %th 
      %tbody
      - @teams.each do |team|
        %tr
          %td= team.person.full_name
          %td
            %table.table
              %thead
              %tbody
                - team.students.each do |member|
                  %tr
                    %td=member.full_name
          %td= link_to 'Editar', edit_team_path(team) 
    = render 'team'

app/views/programed_course_sessions/new.html.haml
%h1 Nueva Sesión

= render 'form'

= link_to 'Atras', programed_course_programed_course_sessions_path(@programed_course_session.programed_course_id), class: "btn btn-default" 

app/views/programed_course_sessions/show.html.haml
%p#notice= notice

%p
  %b Curso Programado:
  = @programed_course_session.programed_course
%p
  %b Numero de Sesión:
  = @programed_course_session.session_number
%p
  %b Tema:
  = @programed_course_session.topic
%p
  %b Fecha:
  = @programed_course_session.date

= link_to 'Editar', edit_programed_course_session_path(@programed_course_session), class: "btn btn-default" 
\|
= link_to 'Atras', programed_course_programed_course_sessions_path(@programed_course_session.programed_course_id), class: "btn btn-default" 