config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :teams do
    resources :team_members
  end

  resource :programed_course_sessions do
    get :autocomplete_person_last_name, on: :collection
  end
  
  resources :courses do 
    resources :programed_courses, shallow: true do
      resources :enrollments, shallow: true 
      resources :programed_course_sessions, shallow: true   
    end
  end
  

  resources :people

  get 'teachers' => 'teachers#index'

   root 'people#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :programed_courses, dependent: :destroy
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student, :class_name => "Person"
  belongs_to :programed_course
  validates :student_id, :presence => true
  validates :programed_course_id, :presence => true
    
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :supervised_programed_courses, class_name: "ProgramedCourse", foreign_key: "supervisor_id"
  has_many :teach_sessions, class_name: "ProgramedCourseSession", foreign_key: "teacher_id"
  has_many :enrollments
  has_many :programed_courses, :through => :enrollments
  has_many :teams, :through => :team_members
  
  def full_name
    "#{first_name} #{second_names} #{last_name} #{second_last_name}"
  end

end

app/models/programed_course.rb
class ProgramedCourse < ActiveRecord::Base
  belongs_to :course
  has_many :programed_course_sessions, dependent: :destroy
  belongs_to :supervisor, :class_name => "Person"
  has_many :enrollments, dependent: :destroy
  has_many :students, :through => :enrollments, dependent: :destroy
  has_many :teams
  
  def course_name
    "#{course.name} empieza #{start_date}"
  end


end

app/models/programed_course_session.rb
class ProgramedCourseSession < ActiveRecord::Base
  belongs_to :programed_course, dependent: :destroy
  belongs_to :teacher, :class_name => "Person", dependent: :destroy



end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :programed_course
  belongs_to :person
  has_many :students, :through => :team_members, dependent: :destroy
  has_many :team_members
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :student, :class_name => "Person"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_for_admin

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.order(:order)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_path, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :order)
    end

    def check_for_admin
      if current_user.try(:admin?)
      else
        redirect_to root_path
      end
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :find_person, only: [:show, :edit, :update, :destroy]
	before_action :find_enrollments, only: [:show]
  before_action :authenticate_user!
  before_action :find_courses_taught, only: [:show]

	def index 
		@person = Person.all
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)

		if @person.save 
			redirect_to @person, notice: "Successful creation of new person"
		else 
			render 'new'
		end 
	end

	def edit 

	end

	def show 

	end

	def update 
		if @person.update(person_params)
			redirect_to @person
		else
			render 'edit'
		end
	end 

	def destroy
		@person.destroy	
		redirect_to root_path, notice: "Successful delete of person"
	end

	private 

	def person_params
		params.require(:person).permit(:first_name, :second_names, :last_name, :birth_date ,:second_last_name, :age, :phone, :email, :address, :teacher ) 
	end

	def find_person
		@person  = Person.find(params[:id])
	end

	def find_enrollments
		@enrollments = Enrollment.where(student: @person)
	end

	def find_courses_taught
		@courses_taught = ProgramedCourseSession.where(teacher_id: @person)
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    get_teachers
  end

  private 
    def get_teachers
      @teachers = Person.where(teacher: true)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController  
  before_action :authenticate_user!
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_path, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:programed_course_id, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper

end

app/helpers/programed_courses_helper.rb
module ProgramedCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/courses/_form.html.haml
= simple_form_for @course do |f|
  - if @course.errors.any?
    #errors
      %p
        = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg
  .row
    .panel-body.col-sm-4
      = f.input :name, label: "Nombre del curso",  input_html: { class: 'form-control' }
      = f.input :description, label: "Descripción",  input_html: { class: 'form-control' }
      = f.input :order, label: "Número de curso (Orden)",  input_html: { class: 'form-control' }

  = f.button :submit, "Guardar"

app/views/courses/edit.html.haml
%h1 Editar Curso

= render 'form'

%br
= link_to 'Mostrar', @course, class: "btn btn-default"
= link_to 'Atras', courses_path, class: "btn btn-default"

app/views/courses/index.html.haml
%h2 Lista de cursos

%table.table
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th Generaciones
      %th Orden
      %th
      %th
      %th

  %tbody
    - @courses.each do |course|
      %tr
        %td= link_to course.name, course_programed_courses_path(course)
        %td= course.description
        %td= course.programed_courses.count
        %td= course.order
        %td= link_to 'Lista de generaciones', course_programed_courses_path(course)
        %td= link_to 'Editar', edit_course_path(course)
        %td= link_to 'Destruir', course, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Nuevo Curso', new_course_path, class: "btn btn-default" 

app/views/courses/new.html.haml
%h1 Nuevo curso

= render 'form'

%br/

= link_to 'Atras', courses_path, class: "btn btn-default" 

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @course.name
%p
  %b Description:
  = @course.description
%p
  %b Order:
  = @course.order

= link_to "Lista de Generaciones", course_programed_courses_path(@course), class: "btn btn-default"
= link_to "Atras", root_path, class: "btn btn-default" 
= link_to "Editar", edit_course_path, class: "btn btn-default" 
= link_to "Destruir", course_path, method: :delete, data: { confirm: "Are you sure ? "},  class: "btn btn-default" 

app/views/teachers/index.html.haml
%h2 Lista de maestros

%table.table
  %thead
    %tr
      %th Nombre
      %th Numero de Sesiones
  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= link_to teacher.full_name, people_path(teacher)
        %td= ProgramedCourseSession.where(teacher: teacher).count

%br